### ISSUE TITLE
Problems with FR phone numbers validation

### ISSUE THREAD

**Issue by apaliavy** [nyaruka/phonenumbers#74]
Hello, 
I noticed the following problem with French phones validation in v1.0.60: 

```
func Normalize(nm string) (string, error) {
        n, err := phonenumbers.Parse(nm, "")
	if err != nil {
		return "", err
	}

	if !phonenumbers.IsValidNumber(n) {
		cc := phonenumbers.GetRegionCodeForCountryCode(int(num.GetCountryCode()))
		return "", fmt.Errorf("%v is an invalid number for region %v", number, cc)
	}
}
```

In v1.0.59 my test works fine. Since the last release, for numbers like `+33691111111` it returns `XXX is an invalid number for region FR` 

Did you change validation rules? I see some changes in [diff](https://github.com/nyaruka/phonenumbers/compare/v1.0.59...v1.0.60#diff-b3e031a89b97461bc730f61fc63924397cc10cb754c0394090ab2843a41843caR2583), is it related?

**Comment by cristaloleg** [comment]
Hi, looking at the demo (validation) page from original `googlei18n/libphonenumber`, looks like it should not be valid. https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

```
****Parsing Result:****
{"country_code":33,"national_number":691111111,"raw_input":"+33691111111","country_code_source":1}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: FR
Result from getNumberType(): UNKNOWN
```

Looks like `v1.0.60` now has a correct behaviour as the original lib, that's why it fails. I'm not 100% sure is this a bug in the original lib or not. Do you know any details about French phone numbers and their exceptions?

**Comment by apaliavy** [comment]
Hm, yes, sorry, it seems like you're right, it behaves exactly like original googlei18n/libphonenumber 

Unfortunately, I don't have enough information about French phone numbers formats so will probably dive into this deeper. 
If this behaviour isn't valid I'll raise a bug for original lib. 

Thanks for your answer!
